metric: COCO
num_classes: 9

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: dataset/shengkai
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: dataset/shengkai

TestDataset:
  !ImageFolder
    anno_path: annotations/instance_val.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/shengkai # if set, anno_path will be 'dataset_dir/anno_path'
